Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://yespandoc.herokuapp.com/"
  copyright: 
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
