Default: &defaults
  database: yespandoc.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yespandoc_test.sqlite3
  <<: *defaults

Staging:
  database: yespandoc_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yespandoc_production.sqlite3
  poolsize: 100
  <<: *defaults
